# Generated by Django 6.0.2 on 2026-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name_short', models.CharField(default='Flaming Gryphon', max_length=120)),
                ('group_name_long', models.CharField(default='The Barony of the Flaming Gryphon', max_length=250)),
                ('admin_name', models.CharField(blank=True, max_length=250)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('coronet', models.CharField(blank=True, help_text='Current Baron and/or Baroness names', max_length=250)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
