# Generated by Django 6.0.2 on 2026-02-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('designator', models.CharField(blank=True, help_text='Group type prefix, e.g. "Marche of", "College of"', max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_key', models.PositiveIntegerField(blank=True, help_text='Original honorkey from legacy database for cross-referencing', null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(blank=True, help_text='Honor type prefix, e.g. "Award of the", "Order of the"', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('abbreviation', models.CharField(blank=True, max_length=15)),
                ('level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('BARONIAL', 'Baronial'), ('CHAMPION', 'Champion'), ('EXTERNAL', 'External/Kingdom')], default='BARONIAL', max_length=10)),
                ('accepts_recommendations', models.BooleanField(default=False)),
                ('is_external', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HonorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='badges/')),
                ('honor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='op.honor')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sca_name', models.CharField(max_length=250)),
                ('mundane_name', models.CharField(blank=True, max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', 'Unspecified')], max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('name_registered', models.BooleanField(default=False)),
                ('device_registered', models.BooleanField(default=False)),
                ('device_blazon', models.TextField(blank=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='op.group')),
            ],
            options={
                'ordering': ['sca_name'],
            },
        ),
        migrations.CreateModel(
            name='Bestowal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_date', models.DateField(blank=True, null=True)),
                ('display_date', models.CharField(blank=True, help_text='Display string for uncertain dates, e.g. "2/?/84"', max_length=13)),
                ('sequence', models.CharField(blank=True, help_text='Ordering within a date for multiple bestowals', max_length=5)),
                ('event_name', models.CharField(blank=True, help_text='Legacy free-text event name from old system', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_draft', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestowals', to='op.event')),
                ('honor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestowals', to='op.honor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestowals', to='op.recipient')),
            ],
            options={
                'ordering': ['sort_date', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='AlternateName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_nickname', models.BooleanField(default=False)),
                ('is_former_name', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_names', to='op.recipient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
