# Generated by Django 6.0.2 on 2026-02-27 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0002_event_group_honor_honorimage_recipient_bestowal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_sca_name', models.CharField(max_length=250)),
                ('nominee_mundane_name', models.CharField(blank=True, max_length=250)),
                ('nominee_gender', models.CharField(blank=True, max_length=1)),
                ('nominee_is_minor', models.BooleanField(default=False)),
                ('justification', models.TextField()),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('GIVEN', 'Given'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('legacy_recommender_sca_name', models.CharField(blank=True, max_length=250)),
                ('legacy_recommender_mundane_name', models.CharField(blank=True, max_length=250)),
                ('legacy_recommender_email', models.CharField(blank=True, max_length=250)),
                ('legacy_recommender_title', models.CharField(blank=True, max_length=250)),
                ('honor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='op.honor')),
                ('nominee_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='op.group')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('scheduled_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_recommendations', to='op.event')),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
    ]
