# Generated by Django 6.0.2 on 2026-02-28 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0003_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED_NO_RESOLUTION', 'Closed (no resolution)')], default='NEW', max_length=25)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('notify_reporter', models.BooleanField(default=True)),
                ('legacy_reporter_sca_name', models.CharField(blank=True, max_length=250)),
                ('legacy_reporter_email', models.CharField(blank=True, max_length=250)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
