# Generated by Django 6.0.2 on 2026-03-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0004_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidrealSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_total', models.IntegerField(default=0)),
                ('new_records', models.IntegerField(default=0)),
                ('status', models.CharField(default='ok', max_length=20)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='MidrealAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sca_name', models.CharField(db_index=True, max_length=250)),
                ('award_name', models.CharField(max_length=250)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_raw', models.CharField(blank=True, help_text='Original date string from Midrealm OP before parsing', max_length=20)),
                ('alternate_names', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('sort_key', models.CharField(blank=True, db_index=True, help_text='terriblesorting value from Midrealm OP, used for delta syncs', max_length=50)),
            ],
            options={
                'ordering': ['sca_name', 'date_received'],
                'unique_together': {('sca_name', 'award_name', 'date_raw')},
            },
        ),
    ]
